[pytest]
addopts = -s -v
markers =
    regression: Маркировка для регрессионых тестов
    form_fields: Маркировка для тестов, связанных с формами
    click_events: Маркировка для тестов, связанных с событиями
    main: Маркировка для тестов, связанных с главной страницей
    popups: Маркировка для тестов, связанных с JS модальными окнами
    slider: Маркировка для тестов, связанных со слайдером
    modals: Маркировка для тестов, связанных с html модальными окнами